# https://www.playframework.com/documentation/latest/Configuration

slick.dbs.default.profile = "slick.jdbc.MySQLProfile$"
slick.dbs.default.db.driver="com.mysql.jdbc.Driver"
slick.dbs.default.db.url="jdbc:mysql://db:3306/db?useSSL=false"
slick.dbs.default.db.user="user"
slick.dbs.default.db.password="pass"


play.evolutions.autoApply = true

play.filters.disabled+=play.filters.csrf.CSRFFilter

play.filters.hosts {
  # Allow requests to example.com, its subdomains, and localhost:9000.
  allowed = ["back:9000", "localhost:9000", "localhost:4200", "editor.swagger.io"]
}

play.http.errorHandler = "be.frol.game.ErrorHandler"

logoutUrl="/login"
