sudo: required
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.28.2
script:
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- set -e; set -o pipefail
- mkdir -p $HOME/.sbt/boot
- export GAME_SBT_CACHE_VOLUME=$HOME
- "bash -x ./build/buildBack.bash"
- "bash -x ./build/buildFront.bash"
- ./build/publish.bash
notifications:
  email:
    on_success: always
    on_failure: always
branches:
  only:
    master
