sudo: required
services:
- docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.0
script:
- set -e; set -o pipefail
- mkdir -p $HOME/.sbt/boot
- export GAME_SBT_CACHE_VOLUME=$HOME
- "bash -x ./build/buildBack.bash"
- docker tag gameback:latest frol2103/gameback:$(git rev-parse HEAD)
- "bash -x ./build/buildFront.bash"
- docker tag gamefront:latest frol2103/gamefront:$(git rev-parse HEAD)
- echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
- docker push frol2103/gameback:$(git rev-parse HEAD)
- docker push frol2103/gamefront:$(git rev-parse HEAD)
notifications:
  email:
    on_success: always
    on_failure: always
branches:
  only:
    master
