sudo: required

language: scala

services:
    - docker
env:
  DOCKER_COMPOSE_VERSION: 1.8.0


script:

    - mkidr -p ./.sbt_cache

    . export GAME_SBT_CACHE_VOLUME="./sbt_cache"

    - ./build/buildBack.bash

    - docker tag gameback:latest frol2103/gameback:$(git rev-parse HEAD)

notifications:
  email:
    on_success: always
    on_failure: always 
