swagger: "2.0"
info:
  description: "online game platform"
  version: "1.0.0"
  title: "Game"
  contact:
    email: "game@frol.be"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "game.frol.be"
basePath: "/api"
tags:
- name: "auth"
  description: "authentification"
- name: "game"
  description: "anything about games in general"
- name: "lostInTranslation"
  description: "Operations about lostInTranslation game"
schemes:
- "https"
- "http"
paths:
  /login:
    post:
      tags:
      - "auth"
      summary: "login"
      description: ""
      operationId: "login"
      parameters:
      - in: "body"
        name: "username"
        description: "login information"
        required: true
        schema:
          type: "string"
      responses: 
        "200":
          description: "ok"

  /user:
    get:
      tags:
        - "auth"
      summary: "connected user"
      description: ""
      operationId: "getConnectedUser"
      responses:
        "200":
          description: "OK"
          schema:
            $ref: "#/definitions/User"

  /game:
    get:
      tags:
        - "game"
      summary: "Get all my games"
      description: ""
      operationId: "getAllGames"
      produces:
        - "application/json"
      responses:
        "200":
          description: "ok"
          schema:
            type: array
            items:
              $ref: "#/definitions/GameDescription"

  /game/create:
    post:
      tags:
      - "game"
      summary: "create a new game"
      description: ""
      operationId: "create a game"
      consumes:
        - "application/json"
      produces:
      - "application/json"
      parameters:
        - in: "body"
          name: "game"
          description: "the game to create"
          required: true
          schema:
            $ref : "#/definitions/GameDescription"
      responses:
        "200":
          description: "ok"
          schema:
            $ref: "#/definitions/Game"

  /game/{uuid}:
    get:
      tags:
        - "game"
      summary: "get a games"
      description: ""
      operationId: "getGame"
      parameters:
        - name: "uuid"
          in: "path"
          required: true
          type: "string"
      produces:
        - "application/json"
      responses:
        "200":
          description: "ok"
          schema:
            $ref: "#/definitions/Game"

  /game/{uuid}/join:
    get:
      tags:
      - "game"
      summary: "join a games"
      description: ""
      operationId: "joinGame"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
      produces:
      - "application/json"
      responses:
        "200":
          description: "ok"
          schema:
            type: array
            items: 
              $ref: "#/definitions/Game"
  
  /game/{uuid}/start:
    get:
      tags:
      - "game"
      summary: "start the game"
      description: ""
      operationId: "startGame"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
      produces:
      - "application/json"
      responses:
        "200":
          description: "ok"
          schema:
            type: array
            items: 
              $ref: "#/definitions/Game"
              
  /game/LostInTranslation/{uuid}:
    get:
      tags:
      - "lostInTranslation"
      summary: "Get an LostInTranslation game"
      description: ""
      operationId: "getGame"
      produces:
      - "application/json"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
      responses:
        "200":
          description: "ok, lost in ctranslation game contains 1 round with no text nor drawing for the first round, 1 round with text or drawing when there is an action to do, all rounds when the match is finished and no round when there is not playable move (the previous player has not made its play)"
          schema:
            type: array
            items: 
              $ref: "#/definitions/LostInTranslationGame"
  
  /game/LostInTranslation/{uuid}/text:
    post:
      tags:
      - "lostInTranslation"
      summary: "add text round in LostInTranslation game"
      description: ""
      operationId: "addTextRound"
      produces:
      - "application/json"
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
      - in: "body"
        name: "text"
        description: "the text"
        required: true
        schema:
          type: string

      responses:
        "200":
          description: "ok"
          schema:
            type: array
            items: 
              $ref: "#/definitions/LostInTranslationGame"
              
  /game/LostInTranslation/{uuid}/drawing:
    post:
      tags:
      - "lostInTranslation"
      summary: "add drawing round in lostInTranslation game"
      description: ""
      operationId: "addDrawingRound"
      produces:
      - "application/json"
      consumes:
        - multipart/form-data
      parameters:
      - name: "uuid"
        in: "path"
        required: true
        type: "string"
      - name: file
        type: file
        in: formData
        required: true

      responses:
        "200":
          description: "ok"
          schema:
            type: array
            items: 
              $ref: "#/definitions/LostInTranslationGame"

  /file/{id}:
    get:
      tags:
        - "file"
      summary: "get a file"
      description: "get a file"
      operationId: "getFile"
      parameters:
        - name: "id"
          in: "path"
          required: true
          type: "string"
      responses:
        "200":
          description: "ok"

  
   
definitions:
  User:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name: 
        type: "string"
      canAdministrageGame:
        type: "boolean"

  GameDescription:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      uuid:
        type: "string"
      startTime:
        type: "string"
        format: "date-time"
      status:
        type: "string"
        enum:
        - "toStart"
        - "inPlay"
        - "finished"
      gameType:
        type: "string"
        enum:
        - "lostInTranslation"
      
  Game:
    type: "object"
    properties:
      description:
        $ref: "#/definitions/GameDescription"
      users:
        type: array
        items:
          $ref: "#/definitions/User"

  
  LostInTranslationGame:
    type: "object"
    properties:
      game:
        $ref: "#/definitions/Game"
      rounds: 
        type: array
        items:
          $ref: "#/definitions/LostInTranslationRound"
  
  
  LostInTranslationRound:
    type: "object"
    properties:
      originalUser:
        $ref: "#/definitions/User"
      roundUser:
        $ref: "#/definitions/User"
      text:
        type: string
      drawing:
        type: string
        description: id of the drawing file, use file api to recover it
    
    
