version: "2"

services:

  back:
    image: frol2103/gameback:#TAG#
    restart: always
    volumes:
        - /srv/conf/env.conf:/app/conf/env.conf
    command: ["/app/bin/back","-Dconfig.file=/app/conf/env.conf"]
        
  front:
    image: frol2103/gamefront:#TAG#
    restart: always
    ports:
      - 80:80

  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - /srv/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=${MYSQL_APP_PASS}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
